#!/usr/bin/env python3
"""Research view renderer: generate all HTML dashboards and Markdown narratives from
timeline.jsonl and traces.jsonl.

All output lives under runs/<CAM>/blackboard/ and is fully derived; it can be deleted
and rebuilt at any time:
  index.html / README.md                    Campaign overview
  timeline.html                             Global event timeline
  missions/<MIS>/index.html / report.md     Mission dashboard + research narrative
  missions/<MIS>/timeline.html              Mission event timeline
  missions/<MIS>/hypotheses/<HYP>/index.html + <HYP>.md   Hypothesis lineage + narrative
  missions/<MIS>/evidence/<EVD>/index.html + <EVD>.md     Evidence page + narrative
  missions/<MIS>/tasks/<TSK>.html           Task trajectory page
  research_snapshot.md                      Aggregated research snapshot for the Director

All HTML is self-contained static (no JavaScript, no external links, inline CSS).
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

from events import build_model, MISSION_PHASES

# ---------------------------------------------------------------------------
# Shared style and page shell
# ---------------------------------------------------------------------------

_CSS = """
:root{color-scheme:light dark;font-family:system-ui,-apple-system,sans-serif;line-height:1.55}
body{max-width:84rem;margin:auto;padding:1.5rem;background:#f7f8fa;color:#202124}
h1{font-size:1.5rem;margin:.2rem 0}h2{font-size:1.15rem;border-bottom:1px solid #dadce0;padding-bottom:.25rem;margin-top:1.4rem}
header{border:1px solid #dadce0;border-radius:.7rem;padding:1rem 1.2rem;background:#fff;margin-bottom:1rem}
nav{border:1px solid #dadce0;border-radius:.7rem;padding:.6rem 1rem;background:#fff;margin-bottom:1rem;font-size:.92rem}
nav a{margin-right:.8rem}
.card{border:1px solid #dadce0;border-radius:.7rem;padding:.9rem 1.1rem;margin:.6rem 0;background:#fff}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(22rem,1fr));gap:.8rem}
.muted{color:#5f6368;font-size:.85rem}
code{background:#f1f3f4;padding:.1rem .35rem;border-radius:.3rem;font-size:.88em}
pre{background:#f1f3f4;border-radius:.5rem;padding:.8rem;overflow-x:auto;font-size:.85rem}
table{border-collapse:collapse;width:100%;background:#fff;font-size:.9rem}
th,td{border:1px solid #dadce0;padding:.4rem .6rem;text-align:left;vertical-align:top}
th{background:#f8f9fa;font-weight:600}
.badge{display:inline-block;padding:.08rem .55rem;border-radius:.9rem;font-size:.78rem;font-weight:600;white-space:nowrap}
.b-h{background:#e8f0fe;color:#1a73e8}.b-s{background:#e6f4ea;color:#137333}.b-w{background:#fef7e0;color:#b06000}
.b-m{background:#8e9bb414;color:#5b21b6}.b-r{background:#fce8e6;color:#c5221f}.b-p{background:#eee;color:#5f6368}
.b-ok{background:#e6f4ea;color:#137333}.b-bad{background:#fce8e6;color:#c5221f}.b-wait{background:#fef7e0;color:#b06000}
.b-neu{background:#f1f3f4;color:#3c4043}
.progress{height:.55rem;background:#e8eaed;border-radius:.3rem;overflow:hidden;margin:.3rem 0}
.progress>div{height:100%;background:#1a73e8;border-radius:.3rem}
.timeline{border-left:2px solid #dadce0;padding-left:1.1rem;margin-left:.3rem}
.tl-item{margin:.55rem 0;position:relative}
.tl-item::before{content:"";position:absolute;left:-1.32rem;top:.35rem;width:.6rem;height:.6rem;border-radius:50%;background:#1a73e8}
.tl-time{color:#80868b;font-size:.78rem}
.chain{border-left:3px solid #1a73e8;padding-left:.9rem;margin:.6rem 0}
.footer{margin-top:1.5rem;color:#80868b;font-size:.82rem;border-top:1px solid #dadce0;padding-top:.6rem}
"""


def _esc(text: object) -> str:
    return html.escape(str(text if text is not None else ""))


def _page(title: str, body: str, crumbs: str = "") -> str:
    return (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n"
        "<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
        f"<title>{_esc(title)}</title>\n<style>{_CSS}</style>\n</head>\n<body>\n"
        f"<header><h1>{_esc(title)}</h1></header>\n"
        f"<nav aria-label=\"Navigation\">{crumbs}</nav>\n<main>\n{body}\n</main>\n"
        "<footer class=\"footer\">Derived view generated by render.py; the authoritative "
        "sources are timeline.jsonl and traces.jsonl at the run root</footer>\n"
        "</body></html>\n"
    )


def _badge(text: str, cls: str = "b-neu") -> str:
    return f'<span class="badge {cls}">{_esc(text)}</span>'


def _assessment_badge(assessment: str) -> str:
    table = {
        "supported": ("Supported", "b-s"),
        "weakened": ("Weakened", "b-w"),
        "mixed": ("Mixed", "b-m"),
        "refuted": ("Refuted", "b-r"),
        "unassessed": ("Unassessed", "b-p"),
    }
    label, cls = table.get(assessment, (assessment, "b-p"))
    return _badge(label, cls)


def _verdict_badge(verdict: str | None) -> str:
    if verdict == "accepted":
        return _badge("Accepted", "b-ok")
    if verdict == "rejected":
        return _badge("Rejected", "b-bad")
    if verdict == "needs_more_work":
        return _badge("Needs more work", "b-wait")
    return _badge("Pending review", "b-p")


def _mission_verdict_badge(verdict: str | None) -> str:
    cls = {"converged": "b-ok", "blocked": "b-bad", "not_testable": "b-bad"}.get(verdict or "", "b-wait")
    return _badge(_esc(verdict or "no verdict"), cls)


def _law_ledger(content: dict) -> dict:
    ledger = content.get("law_quality_ledger") or {}
    return ledger if isinstance(ledger, dict) else {}


def _law_ledger_html(content: dict) -> str:
    ledger = _law_ledger(content)
    if not ledger:
        return ""
    criteria = ledger.get("criteria") or {}
    criteria_html = "".join(
        f"<li>{_esc(str(k))}: {_esc(str(v))}</li>"
        for k, v in criteria.items()
    ) if isinstance(criteria, dict) else ""
    gaps = "".join(f"<li>{_esc(str(g))}</li>" for g in ledger.get("gaps") or [])
    return (
        f'<p><strong>Law candidate:</strong> {_esc(ledger.get("law_candidate") or "")}</p>'
        f'<p><strong>Law maturity:</strong> {_esc(ledger.get("maturity") or "?")}</p>'
        + (f'<p><strong>Law-quality criteria:</strong></p><ul>{criteria_html}</ul>' if criteria_html else "")
        + (f'<p><strong>Law-quality gaps:</strong></p><ul>{gaps}</ul>' if gaps else "")
    )


def _law_ledger_md(content: dict) -> list[str]:
    ledger = _law_ledger(content)
    if not ledger:
        return []
    lines = [
        f"  - Law candidate: {ledger.get('law_candidate', '')}",
        f"  - Law maturity: {ledger.get('maturity', '?')}",
    ]
    criteria = ledger.get("criteria") or {}
    if isinstance(criteria, dict):
        lines.extend(f"    - {key}: {value}" for key, value in criteria.items())
    lines.extend(f"  - Law gap: {gap}" for gap in ledger.get("gaps") or [])
    return lines


def _frontier_items(content: dict) -> list[dict]:
    return [i for i in content.get("research_frontier") or [] if isinstance(i, dict)]


def _frontier_html(content: dict) -> str:
    items = _frontier_items(content)
    if not items:
        return ""
    html_items = "".join(
        f'<li>{_esc(str(i.get("move") or "?"))} · {_esc(str(i.get("priority") or "?"))} · '
        f'{_esc(str(i.get("quality_gap") or ""))} — {_esc(str(i.get("expected_decision_change") or ""))}</li>'
        for i in items
    )
    return f'<p><strong>Research frontier:</strong></p><ul>{html_items}</ul>'


def _frontier_md(content: dict) -> list[str]:
    return [
        f"  - Frontier: {i.get('move', '?')} · {i.get('priority', '?')} · "
        f"{i.get('quality_gap', '')} — {i.get('expected_decision_change', '')}"
        for i in _frontier_items(content)
    ]



def _direction_label(direction: str | None) -> str:
    return {"support": "Support", "challenge": "Challenge", "mixed": "Mixed"}.get(direction or "", direction or "—")


def _phase_badge(phase: str) -> str:
    color = {
        "committed": "b-ok", "blocked": "b-bad", "rejected": "b-bad", "cancelled": "b-bad",
        "executing": "b-wait",
    }.get(phase, "b-neu")
    return _badge(phase, color)


def _progress(current: str) -> str:
    if current in MISSION_PHASES:
        idx = MISSION_PHASES.index(current) + 1
        pct = int(idx / len(MISSION_PHASES) * 100)
    else:
        pct = 100
    return f'<div class="progress"><div style="width:{pct}%"></div></div>'


def _event_row(ev: dict) -> str:
    role = _esc(ev.get("role") or "—")
    etype = _esc(ev.get("type") or "")
    time = _esc((ev.get("created_at") or "")[:19])
    mid = _esc(ev.get("mission_id") or "")
    extra = f" · {mid}" if mid else ""
    return (
        f'<div class="tl-item">'
        f'<span class="tl-time">{time}</span> '
        f'{_badge(etype, "b-neu")} {_badge(role, "b-neu")}{_esc(extra)}'
        f'<br>{_esc(ev.get("summary") or "")}'
        f'</div>'
    )


def _event_card(ev: dict) -> str:
    rows = []
    for key, label in (
        ("mission_id", "Mission"), ("task_id", "Task"), ("role", "Role"),
        ("status", "Status"), ("replies_to", "Reply to"),
    ):
        v = ev.get(key)
        if v:
            rows.append(f"<dt>{label}</dt><dd><code>{_esc(v)}</code></dd>")
    content = ev.get("content") or {}
    if isinstance(content, dict):
        for key, label in (
            ("hypothesis_id", "Hypothesis"), ("evidence_id", "Evidence"), ("verdict", "Verdict"),
            ("operation", "Operation"), ("tool_name", "Tool"), ("mission_verdict", "Mission verdict"),
        ):
            v = content.get(key)
            if v:
                rows.append(f"<dt>{label}</dt><dd>{_esc(v)}</dd>")
    dl = "<dl>" + "".join(rows) + "</dl>" if rows else ""
    return (
        f'<div class="card"><span class="tl-time">{_esc((ev.get("created_at") or "")[:19])}</span> '
        f'{_badge(_esc(ev.get("type") or ""), "b-neu")} '
        f'{_badge(_esc(ev.get("role") or ""), "b-neu")} {_badge(_esc(ev.get("status") or ""), "b-p")}'
        f'<p><strong>{_esc(ev.get("summary") or "")}</strong></p>'
        f"{dl}</div>"
    )


# ---------------------------------------------------------------------------
# Director directives views
# ---------------------------------------------------------------------------

def _md_inline(text: str) -> str:
    t = html.escape(text)
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"`([^`]+)`", r"<code>\1</code>", t)
    return t


def _md_simple(text: str) -> str:
    """Minimal, dependency-free Markdown -> HTML for the directive narratives."""
    out: list[str] = []
    para: list[str] = []
    list_open = False

    def flush() -> None:
        nonlocal list_open
        if list_open:
            out.append("</ul>")
            list_open = False
        if para:
            out.append("<p>" + " ".join(para) + "</p>")
            para.clear()

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            flush()
        elif line.startswith("### "):
            flush(); out.append(f"<h4>{_esc(line[4:])}</h4>")
        elif line.startswith("## "):
            flush(); out.append(f"<h3>{_esc(line[3:])}</h3>")
        elif line.startswith("# "):
            flush(); out.append(f"<h2>{_esc(line[2:])}</h2>")
        elif line.startswith("- ") or line.startswith("* "):
            if not list_open:
                flush(); out.append("<ul>")
                list_open = True
            out.append(f"<li>{_md_inline(line[2:])}</li>")
        else:
            if list_open:
                out.append("</ul>")
                list_open = False
            para.append(_md_inline(line))
    flush()
    return "".join(out)


def _scan_directives(run_root: Path) -> list[dict]:
    """Scan blackboard/directives (including consumed/) and return per-round info."""
    ddir = run_root / "blackboard" / "directives"
    if not ddir.is_dir():
        return []
    groups: dict[str, dict] = {}
    for path in sorted(ddir.rglob("round-*")):
        if not path.is_dir():
            continue
        g = groups.setdefault(path.name, {"round": path.name, "proposal": {}, "decision": {}})
        for key in ("proposal", "decision"):
            jp = path / f"{key}.json"
            if jp.is_file():
                try:
                    g[key] = json.loads(jp.read_text(encoding="utf-8"))
                except (ValueError, OSError):
                    g[key] = {}
            mp = path / f"{key}.md"
            if mp.is_file():
                g[key]["_md"] = mp.read_text(encoding="utf-8")
    return [groups[k] for k in sorted(groups)]


def _directive_payload(d: dict) -> dict:
    """Return the meaningful payload of a directive json (unwrap the 'mission' key)."""
    if isinstance(d.get("mission"), dict):
        return d["mission"]
    return d


def _directive_field_rows(data: dict) -> str:
    rows = []
    for key, label in (
        ("research_question", "Research question"),
        ("expected_knowledge_gain", "Expected knowledge gain"),
        ("narrowing_rationale", "Narrowing rationale"),
    ):
        v = data.get(key)
        if v:
            rows.append(f"<dt>{label}</dt><dd>{_esc(v)}</dd>")
    for key, label in (
        ("hypothesis_directions", "Hypothesis directions"),
        ("scope", "Scope"),
        ("non_goals", "Non-goals"),
        ("boundary_extension_targets", "Boundary extension targets"),
        ("exit_conditions", "Exit conditions"),
    ):
        v = data.get(key)
        if v:
            items = "".join(f"<li>{_esc(i)}</li>" for i in v) if isinstance(v, list) else f"<li>{_esc(v)}</li>"
            rows.append(f"<dt>{label}</dt><dd><ul>{items}</ul></dd>")
    return f"<dl>{''.join(rows)}</dl>" if rows else ""


def render_directive_page(run_root: Path, out_dir: Path, round_name: str, data: dict, kind: str) -> Path | None:
    """Write blackboard/directives/<round>/<kind>.html for one directive. Return its path."""
    payload = _directive_payload(data)
    if not payload and not data.get("_md"):
        return None
    ddir = out_dir / "directives" / round_name
    ddir.mkdir(parents=True, exist_ok=True)
    nav = (
        '<a href="../../index.html">Overview</a> '
        '<a href="../../timeline.html">Timeline</a> '
        f'<a href="{_esc(kind)}.md">Raw {_esc(kind)}.md</a>'
    )
    md_html = f"<h2>Detailed narrative</h2>{_md_simple(data.get('_md') or '')}" if data.get("_md") else ""
    body = f"<h2>{_esc(kind.title())} fields</h2><div class=\"card\">{_directive_field_rows(payload)}</div>{md_html}"
    path = ddir / f"{kind}.html"
    path.write_text(_page(f"Director {kind.title()} · {round_name}", body, nav), encoding="utf-8")
    return path


def _directives_index_html(run_root: Path) -> str:
    """HTML block for the campaign overview: one card per round with a proposal/decision."""
    rounds = _scan_directives(run_root)
    if not rounds:
        return "<h2>Director directives (0)</h2><p class=\"muted\">No directives yet.</p>"
    cards = []
    for g in rounds:
        rname = g["round"]
        prop, dec = g["proposal"], g["decision"]
        prop_payload = _directive_payload(prop)
        bits = []
        if prop_payload or prop.get("_md"):
            name = prop_payload.get("name") or "Mission proposal"
            question = prop_payload.get("research_question") or prop.get("summary") or ""
            bits.append(
                f'<p><strong>Proposal:</strong> {_esc(name)}</p>'
                + (f'<p class="muted">{_esc(question)}</p>' if question else "")
                + f'<a href="directives/{_esc(rname)}/proposal.html">Proposal details →</a>'
            )
        if dec or dec.get("_md"):
            rec = dec.get("recommendation") or dec.get("directive_type") or "decision"
            rationale = dec.get("rationale") or dec.get("summary") or ""
            bits.append(
                f'<p><strong>Decision:</strong> {_badge(_esc(rec), "b-neu")}</p>'
                + (f'<p class="muted">{_esc(rationale)}</p>' if rationale else "")
                + f'<a href="directives/{_esc(rname)}/decision.html">Decision details →</a>'
            )
        if bits:
            cards.append(f'<div class="card"><strong>Round <code>{_esc(rname)}</code></strong>' + "".join(bits) + "</div>")
    return f"<h2>Director directives ({len(rounds)})</h2>" + ("".join(cards) if cards else "<p class=\"muted\">No directives yet.</p>")


def render_directives_pages(run_root: Path, out_dir: Path) -> list[str]:
    """Write the per-round directive detail pages. Return relative written paths."""
    written = []
    for g in _scan_directives(run_root):
        rname = g["round"]
        for kind in ("proposal", "decision"):
            p = render_directive_page(run_root, out_dir, rname, g[kind], kind)
            if p:
                written.append(str(p.relative_to(run_root)))
    return written


# ---------------------------------------------------------------------------
# Experience library view
# ---------------------------------------------------------------------------

_EXPERIENCE_LABELS = {
    "env": "Environment",
    "tool": "Tools",
    "script": "Scripts & pipelines",
    "workflow": "Workflow",
    "pitfall": "Pitfalls",
}


def render_experience(run_root: Path, out_dir: Path) -> Path:
    """Write blackboard/experience.html: engineering knowledge, grouped by category."""
    from events import experience_list

    entries = experience_list(run_root)
    nav = '<a href="index.html">Overview</a> <a href="timeline.html">Timeline</a>'
    intro = (
        "<p class=\"muted\">Engineering knowledge only (environment, tools, scripts, "
        "workflow, pitfalls) - never chemical conclusions; those live in the evidence "
        "pipeline.</p>"
    )
    if not entries:
        body = "<h2>Experience library</h2>" + intro + "<p class=\"muted\">No entries yet.</p>"
        path = out_dir / "experience.html"
        path.write_text(_page("Experience Library", body, nav), encoding="utf-8")
        return path

    groups: dict[str, list] = {}
    for e in entries:
        groups.setdefault(e.get("category") or "other", []).append(e)
    blocks = []
    for cat in sorted(groups):
        cards = ""
        for e in groups[cat]:
            src = []
            if e.get("source_role"):
                src.append(f"role {_esc(e['source_role'])}")
            if e.get("source_task"):
                src.append(f"<code>{_esc(e['source_task'])}</code>")
            cards += (
                f'<div class="card"><span class="tl-time">{_esc((e.get("created_at") or "")[:19])}</span> '
                f'{_badge(_esc(e.get("category") or ""), "b-neu")} '
                f'<strong>{_esc(e.get("summary") or "")}</strong>'
                + (f'<p>{_esc(e.get("detail") or "")}</p>' if e.get("detail") else "")
                + (f'<p class="muted">Source: {" · ".join(src)}</p>' if src else "")
                + "</div>"
            )
        label = _EXPERIENCE_LABELS.get(cat, cat)
        blocks.append(f"<h2>{_esc(label)} ({len(groups[cat])})</h2>{cards}")
    body = "<h2>Experience library</h2>" + intro + "".join(blocks)
    path = out_dir / "experience.html"
    path.write_text(_page("Experience Library", body, nav), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Campaign overview
# ---------------------------------------------------------------------------

def _mission_report_html(report: dict) -> str:
    """Render one mission_report event as an HTML card."""
    content = report.get("content") or {}
    updates = "".join(
        f'<li><code>{_esc(u.get("hypothesis_id") or "?")}</code>: '
        f'{_esc(u.get("old_assessment") or "?")} → {_esc(u.get("new_assessment") or "?")} — '
        f'{_esc(u.get("rationale") or "")}</li>'
        for u in content.get("hypothesis_updates") or []
    )
    evidence = "".join(
        f'<li><code>{_esc(e.get("evidence_id") or "?")}</code> · '
        f'{_verdict_badge(e.get("verdict"))} — {_esc(e.get("why") or "")}</li>'
        for e in content.get("evidence_summary") or []
    )
    questions = "".join(f"<li>{_esc(q)}</li>" for q in content.get("open_questions") or [])
    return (
        f'<div class="card">'
        f'<span class="tl-time">{_esc((report.get("created_at") or "")[:19])}</span> '
        f'{_mission_verdict_badge(content.get("mission_verdict"))} '
        f'<strong>{_esc(report.get("summary") or "")}</strong>'
        + _law_ledger_html(content)
        + _frontier_html(content)
        + (f'<p><strong>Hypothesis updates:</strong></p><ul>{updates}</ul>' if updates else "")
        + (f'<p><strong>Evidence summary:</strong></p><ul>{evidence}</ul>' if evidence else "")
        + (f'<p><strong>Open questions:</strong></p><ul>{questions}</ul>' if questions else "")
        + (f'<p><em>Contribution:</em> {_esc(content.get("contribution_to_research") or "")}</p>' if content.get("contribution_to_research") else "")
        + "</div>"
    )


def render_campaign(run_root: Path, model: dict, out_dir: Path) -> tuple[str, str]:
    """Write blackboard/index.html and blackboard/README.md. Return both paths."""
    camp = model["campaign"]
    missions = model["missions"]
    hypotheses = model["hypotheses"]
    evidence = model["evidence"]
    timeline = model["timeline"]
    reports = model["mission_reports"]

    status_badge = _badge(_esc(camp.get("status") or "active"), "b-neu")
    header_info = (
        f'<p>{_esc(camp.get("objective") or "")}</p>'
        f'<p class="muted">Campaign status: {status_badge} · created {_esc((camp.get("created_at") or "")[:19])}</p>'
    )

    hyp_cards = []
    for hid, h in sorted(hypotheses.items()):
        counts = _evidence_counts(evidence, hid)
        hyp_cards.append(
            f'<div class="card"><strong>HYP <code>{_esc(hid)}</code></strong> '
            f'{_assessment_badge(h["assessment"])} {_badge(_esc(h.get("status") or "active"), "b-neu")}'
            f'<p>{_esc(h["claim"])}</p>'
            f'<p class="muted">{len(h["versions"])} versions · {counts_to(hid, evidence)}</p>'
            f'<a href="missions/{_esc(h.get("mission_id") or "")}/hypotheses/{_esc(hid)}/index.html">Lineage details →</a></div>'
        )
    hyp_section = (
        f"<h2>Current hypotheses ({len(hypotheses)})</h2>"
        + (f'<div class="grid">{"".join(hyp_cards)}</div>' if hyp_cards else "<p class=\"muted\">No hypotheses yet.</p>")
    )

    mission_cards = []
    for mid, m in sorted(missions.items()):
        hcount = sum(1 for h in hypotheses.values() if h.get("mission_id") == mid)
        ecount = sum(1 for e in evidence.values() if e.get("mission_id") == mid)
        mission_cards.append(
            f'<div class="card"><strong>Mission <code>{_esc(mid)}</code></strong> '
            f'{_phase_badge(m["phase"])}{_progress(m["phase"])}'
            f'<p>{_esc(m.get("question") or "")}</p>'
            f'<p class="muted">{hcount} hypotheses · {ecount} evidence · created {_esc((m.get("created_at") or "")[:10])}</p>'
            f'<a href="missions/{_esc(mid)}/index.html">Open dashboard →</a></div>'
        )
    mission_section = (
        f"<h2>Missions ({len(missions)})</h2>"
        + (f'<div class="grid">{"".join(mission_cards)}</div>' if mission_cards else "<p class=\"muted\">No missions yet.</p>")
    )

    report_section = ""
    if reports:
        report_section = (
            f"<h2>Latest mission report</h2>{_mission_report_html(reports[-1])}"
        )

    recent = timeline[-10:][::-1]
    recent_html = (
        '<h2>Latest activity</h2><div class="timeline">'
        + ("".join(_event_row(ev) for ev in recent) if recent else "<p class=\"muted\">No events yet.</p>")
        + "</div>"
    )

    decisions = model["decisions"]
    final_law_html = ""
    if decisions:
        dcontent = decisions[-1].get("content") or {}
        fl = dcontent.get("final_law") or {}
        if fl:
            _oq = fl.get("open_questions") or ""
            if isinstance(_oq, list):
                _oq = "; ".join(
                    (str(x.get("question") or x) + f" [{x.get('status')}]" if isinstance(x, dict) else str(x))
                    for x in _oq
                )
            _fh = fl.get("final_hypotheses") or ""
            if isinstance(_fh, list):
                _fh = "; ".join(str(x) for x in _fh)
            fl_html = (
                f'<p><strong>{_esc(fl.get("statement") or "")}</strong></p>'
                + (f'<p><em>Final hypotheses:</em> {_esc(_fh)}</p>' if _fh else "")
                + (f'<p><em>Evidence support:</em> {_esc(fl.get("evidence_support") or "")}</p>' if fl.get("evidence_support") else "")
                + (f'<p><em>Boundaries:</em> {_esc(fl.get("boundaries") or "")}</p>' if fl.get("boundaries") else "")
                + (f'<p><em>Recommendation:</em> {_esc(fl.get("recommendation") or "")}</p>' if fl.get("recommendation") else "")
                + (f'<p><em>Open questions:</em> {_esc(_oq)}</p>' if _oq else "")
            )
            final_law_html = f"<h2>Final scientific law</h2><div class=\"card\">{fl_html}</div>"

    if decisions:
        last_d = decisions[-1]
        decision_html = (
            f"<h2>Most recent decision</h2><div class=\"card\">"
            f'<span class="tl-time">{_esc(last_d["created_at"][:19])}</span>'
            f'<p>{_esc(last_d["summary"])}</p></div>'
        )
    else:
        decision_html = ""

    nav = (
        '<a href="timeline.html">Global timeline</a> '
        '<a href="experience.html">Experience</a> '
        '<a href="research_snapshot.md">Research snapshot</a>'
        + "".join(f'<a href="missions/{_esc(mid)}/index.html">MIS</a>' for mid in missions)
        + '<a href="README.md">Narrative</a>'
    )
    body = header_info + final_law_html + _directives_index_html(run_root) + report_section + hyp_section + mission_section + recent_html + decision_html
    index_html = _page(f"Campaign Overview · {_esc(camp.get('id') or 'run')}", body, nav)
    index_path = out_dir / "index.html"
    index_path.write_text(index_html, encoding="utf-8")

    lines = [
        "# Campaign Overview",
        "",
        f"- Campaign: `{camp.get('id') or '—'}`  Status: {camp.get('status') or 'active'}",
        f"- Objective: {camp.get('objective') or '—'}",
        "",
        "## Current hypotheses",
        "",
    ]
    for hid, h in sorted(hypotheses.items()):
        lines += [
            f"### {hid}  [{h['assessment']}]",
            f"{h['claim']}",
            f"- Versions: {len(h['versions'])}; evidence: {counts_to(hid, evidence)}",
            "",
        ]
    lines += ["## Missions", ""]
    for mid, m in sorted(missions.items()):
        lines.append(f"- `{mid}`  phase `{m['phase']}`  question: {m.get('question') or '—'}")
    lines += ["", "## Latest mission reports", ""]
    for r in reports[-3:]:
        content = r.get("content") or {}
        lines.append(
            f"- ({r.get('created_at', '')[:19]}) `{content.get('mission_verdict', '?')}` "
            f"{r.get('summary', '')}"
        )
    lines += ["", "## Director directives", ""]
    _rounds = _scan_directives(run_root)
    for g in _rounds:
        rname = g["round"]
        prop = _directive_payload(g["proposal"])
        dec = g["decision"]
        if prop or g["proposal"].get("_md"):
            lines.append(
                f"- Round `{rname}` proposal: {prop.get('name') or '—'} — "
                f"{prop.get('research_question') or g['proposal'].get('summary') or 'see details'}"
            )
        if dec or dec.get("_md"):
            lines.append(f"- Round `{rname}` decision: {dec.get('recommendation') or '—'} — {dec.get('rationale') or dec.get('summary') or ''}")
    if not _rounds:
        lines.append("- No directives yet.")
    lines += ["", "## Latest events", ""]
    for ev in reversed(timeline[-15:]):
        lines.append(f"- ({ev.get('created_at', '')[:19]}) `{ev.get('role', '—')}` {ev.get('summary', '')}")
    lines += ["## Final scientific law", ""]
    if decisions:
        fl = (decisions[-1].get("content") or {}).get("final_law") or {}
        if fl:
            oq = fl.get("open_questions") or ""
            if isinstance(oq, list):
                oq = "; ".join(
                    (str(x.get("question") or x) + f" [{x.get('status')}]" if isinstance(x, dict) else str(x))
                    for x in oq
                )
            fh = fl.get("final_hypotheses") or ""
            if isinstance(fh, list):
                fh = "; ".join(str(x) for x in fh)
            lines += [
                f"- Statement: {fl.get('statement') or '—'}",
                f"- Final hypotheses: {fh or '—'}",
                f"- Evidence support: {fl.get('evidence_support') or '—'}",
                f"- Boundaries: {fl.get('boundaries') or '—'}",
                f"- Recommendation: {fl.get('recommendation') or '—'}",
                f"- Open questions: {oq or '—'}",
            ]
        else:
            lines.append("- Not reached yet.")
    else:
        lines.append("- Not reached yet.")
    lines += ["", "## Most recent decision", ""]
    if decisions:
        for d in decisions[-5:]:
            lines.append(f"- ({d['created_at'][:19]}) {d['summary']}")
    else:
        lines.append("- None yet.")
    md = "\n".join(lines) + "\n"
    md_path = out_dir / "README.md"
    md_path.write_text(md, encoding="utf-8")
    return str(index_path.relative_to(run_root)), str(md_path.relative_to(run_root))


def counts_to(hid: str, evidence: dict) -> str:
    c = _evidence_counts(evidence, hid)
    return (
        f"support {c['support']} / challenge {c['challenge']} / mixed {c['mixed']} "
        f"/ pending {c['pending']} / rejected {c['rejected']}"
    )


def _evidence_counts(evidence: dict, hypothesis_id: str | None) -> dict:
    counts = {"support": 0, "challenge": 0, "mixed": 0, "pending": 0, "rejected": 0}
    for e in evidence.values():
        if e.get("hypothesis_id") != hypothesis_id:
            continue
        verdict = e.get("verdict")
        if verdict == "rejected":
            counts["rejected"] += 1
        elif verdict != "accepted":
            counts["pending"] += 1
        else:
            direction = e.get("direction") or "support"
            counts[direction if direction in counts else "mixed"] += 1
    return counts


# ---------------------------------------------------------------------------
# Global timeline
# ---------------------------------------------------------------------------

def render_global_timeline(run_root: Path, model: dict, out_dir: Path) -> Path:
    body = (
        '<h2>Global event timeline</h2><div class="timeline">'
        + "".join(_event_row(ev) for ev in model["timeline"])
        + "</div>"
    )
    path = out_dir / "timeline.html"
    path.write_text(
        _page("Global Timeline", body, '<a href="index.html">← Overview</a>'), encoding="utf-8"
    )
    return path


# ---------------------------------------------------------------------------
# Research snapshot (Director input)
# ---------------------------------------------------------------------------

def render_research_snapshot(run_root: Path, model: dict, out_dir: Path) -> Path:
    """Write blackboard/research_snapshot.md: the aggregated snapshot for the Director."""
    camp = model["campaign"]
    lines = [
        "# Research Snapshot",
        "",
        f"- Campaign: `{camp.get('id') or '—'}`  Status: {camp.get('status') or 'active'}",
        f"- Objective: {camp.get('objective') or '—'}",
        "",
    ]

    lines += ["## Hypotheses and detailed rationale", ""]
    if not model["hypotheses"]:
        lines.append("- No hypotheses yet.")
    for hid, h in sorted(model["hypotheses"].items()):
        lines += [f"### {hid}  [{h['assessment']}]  lifecycle: {h.get('status') or 'active'}", ""]
        for i, v in enumerate(h["versions"], 1):
            lines += [
                f"- v{i} ({v.get('operation', '?')}, {(v.get('created_at') or '')[:19]}): {v['claim']}",
                f"  - Change summary: {v.get('change_summary') or '—'}",
            ]
        lines.append("")

    lines += ["## Evidence and review reasons", ""]
    if not model["evidence"]:
        lines.append("- No evidence yet.")
    for eid, e in sorted(model["evidence"].items()):
        lines += [
            f"- `{eid}` → {e.get('hypothesis_id') or '—'} · direction "
            f"{_direction_label(e.get('direction'))} · verdict {e.get('verdict') or 'pending'}",
            f"  - Review: {e.get('verdict_reason') or 'no review yet'}",
            f"  - Summary: {e.get('summary') or ''}",
        ]
    lines.append("")

    lines += ["## Unresolved alternatives and open questions", ""]
    open_items = []
    for r in model["mission_reports"]:
        content = r.get("content") or {}
        open_items += content.get("unresolved_alternatives") or []
        open_items += content.get("open_questions") or []
    if open_items:
        for item in open_items:
            lines.append(f"- {item}")
    else:
        lines.append("- None recorded yet.")
    lines.append("")

    lines += ["## Capability notes", ""]
    cap_notes = []
    for r in model["mission_reports"]:
        cap_notes += (r.get("content") or {}).get("capability_notes") or []
    if cap_notes:
        for n in cap_notes:
            lines.append(f"- {n}")
    else:
        lines.append("- None recorded yet.")
    lines.append("")

    lines += ["## Budget", ""]
    snap = {}
    snap_path = run_root / "config.snapshot.json"
    if snap_path.is_file():
        import json as _json

        try:
            snap = _json.loads(snap_path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            snap = {}
    outer = (snap.get("campaign") or {}).get("max_outer_rounds")
    inner = (snap.get("mission") or {}).get("max_inner_rounds")
    propose = (snap.get("director") or {}).get("propose_count")
    completed = sum(1 for m in model["missions"].values() if m.get("phase") == "committed")
    if outer is not None:
        lines.append(f"- Outer rounds: {completed} completed of at most {outer} (propose_count={propose})")
    if inner is not None:
        lines.append(f"- Inner rounds per Mission: at most {inner}")
    lines.append("")

    path = out_dir / "research_snapshot.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Mission views
# ---------------------------------------------------------------------------

def _mission_events(model: dict, mission_id: str) -> list[dict]:
    return [ev for ev in model["timeline"] if ev.get("mission_id") == mission_id]


def render_mission(run_root: Path, model: dict, mission_id: str, out_dir: Path) -> Path:
    """Write the mission index.html, report.md, and timeline.html. Return the index path."""
    m = model["missions"].get(mission_id)
    if m is None:
        raise ValueError(f"Mission does not exist: {mission_id}")
    mdir = out_dir / "missions" / mission_id
    mdir.mkdir(parents=True, exist_ok=True)

    evs = _mission_events(model, mission_id)
    hyp_ids = sorted(hid for hid, h in model["hypotheses"].items() if h.get("mission_id") == mission_id)

    nav = (
        '<a href="../../../index.html">Overview</a> '
        '<a href="timeline.html">Timeline</a> '
        '<a href="report.md">Report</a> '
    )
    header = (
        f'<p><code>{_esc(mission_id)}</code> · phase: {_phase_badge(m["phase"])}</p>'
        f'{_progress(m["phase"])}'
        f'<p><strong>Research question:</strong> {_esc(m.get("question") or "—")}</p>'
    )

    hyp_cards = []
    for hid in hyp_ids:
        h = model["hypotheses"][hid]
        hyp_cards.append(
            f'<div class="card"><strong>HYP <code>{_esc(hid)}</code></strong> '
            f'{_assessment_badge(h["assessment"])} {_badge(_esc(h.get("status") or "active"), "b-neu")}'
            f'<p>{_esc(h["claim"])}</p>'
            f'<p class="muted">{len(h["versions"])} versions · {counts_to(hid, model["evidence"])}</p>'
            f'<a href="hypotheses/{_esc(hid)}/index.html">Lineage and evidence →</a></div>'
        )
    hyp_section = (
        f"<h2>Hypotheses ({len(hyp_cards)})</h2>"
        + (f'<div class="grid">{"".join(hyp_cards)}</div>' if hyp_cards else "<p class=\"muted\">No hypotheses yet.</p>")
    )

    ev_rows = []
    for eid, e in sorted(model["evidence"].items()):
        if e.get("mission_id") != mission_id:
            continue
        ev_rows.append(
            "<tr>"
            f"<td><code>{_esc(eid)}</code></td>"
            f"<td><code>{_esc(e.get('hypothesis_id') or '—')}</code></td>"
            f"<td>{_esc(_direction_label(e.get('direction')))}</td>"
            f"<td>{_verdict_badge(e.get('verdict'))}</td>"
            f"<td>{_esc(e.get('summary') or '')}</td>"
            f'<td><a href="evidence/{_esc(eid)}/index.html">Details</a></td>'
            "</tr>"
        )
    ev_section = (
        f"<h2>Evidence ({len(ev_rows)})</h2>"
        + (
            '<table><thead><tr><th>Evidence</th><th>Hypothesis</th><th>Direction</th><th>Verdict</th><th>Summary</th><th></th></tr></thead>'
            + "".join(ev_rows) + "</table>"
            if ev_rows
            else "<p class=\"muted\">No evidence yet.</p>"
        )
    )

    reports = [r for r in model["mission_reports"] if r.get("mission_id") == mission_id]
    report_section = (
        f"<h2>Mission report</h2>"
        + ("".join(_mission_report_html(r) for r in reports) if reports else "<p class=\"muted\">No mission report yet.</p>")
    )

    dec_empty = [ev for ev in evs if ev.get("type") == "decision"]
    dec_html = "".join(_event_card(ev) for ev in dec_empty) or "<p class=\"muted\">No decisions yet.</p>"
    dec_section = f"<h2>Decisions</h2>{dec_html}"

    chain_html = _render_chain(model, mission_id)
    chain_section = f"<h2>Agent exchange</h2>{chain_html}"

    task_links = []
    for tid, t in sorted(model["tasks"].items()):
        if any(ev.get("mission_id") == mission_id for ev in model["timeline"] if ev.get("task_id") == tid):
            task_links.append(
                f'<li><code>{_esc(tid)}</code> · {_badge(_esc(t.get("role") or "—"), "b-neu")} '
                f'· {len(t["events"])} trace nodes · <a href="tasks/{_esc(tid)}.html">View trace →</a></li>'
            )
    task_section = (
        "<h2>Task traces</h2><ul>"
        + ("".join(task_links) if task_links else "<li class=\"muted\">No tasks yet.</li>")
        + "</ul>"
        + f'<p><a href="tasks/index.html">Open the task board →</a></p>'
    )

    recent = evs[-10:][::-1]
    recent_html = (
        '<h2>Latest events</h2><div class="timeline">'
        + ("".join(_event_row(ev) for ev in recent) if recent else "<p class=\"muted\">No events yet.</p>")
        + "</div>"
    )

    body = header + report_section + hyp_section + ev_section + dec_section + chain_section + task_section + recent_html
    index_path = mdir / "index.html"
    index_path.write_text(_page(f"Mission Dashboard · {mission_id}", body, nav), encoding="utf-8")

    report = _mission_report_md(model, mission_id, m, evs, hyp_ids, reports)
    report_path = mdir / "report.md"
    report_path.write_text(report, encoding="utf-8")

    tl_body = (
        '<h2>Mission event timeline</h2><div class="timeline">'
        + "".join(_event_row(ev) for ev in evs) + "</div>"
    )
    tl_path = mdir / "timeline.html"
    tl_path.write_text(_page(f"Mission Timeline · {mission_id}", tl_body, nav), encoding="utf-8")

    return index_path


def _mission_report_md(model: dict, mission_id: str, m: dict, evs: list[dict], hyp_ids: list[str], reports: list[dict]) -> str:
    lines = [
        f"# Mission {mission_id} Report",
        "",
        f"- Phase: `{m['phase']}`",
        f"- Research question: {m.get('question') or '—'}",
        "",
        "## Mission synthesis",
        "",
    ]
    for r in reports:
        content = r.get("content") or {}
        lines.append(f"- Verdict: `{content.get('mission_verdict', '?')}` — {r.get('summary', '')}")
        lines.extend(_law_ledger_md(content))
        lines.extend(_frontier_md(content))
        for u in content.get("hypothesis_updates") or []:
            lines.append(
                f"  - {u.get('hypothesis_id')}: {u.get('old_assessment')} → "
                f"{u.get('new_assessment')} — {u.get('rationale', '')}"
            )
        for e in content.get("evidence_summary") or []:
            lines.append(f"  - Evidence {e.get('evidence_id')} · {e.get('verdict')} — {e.get('why', '')}")
        for q in content.get("open_questions") or []:
            lines.append(f"  - Open: {q}")
        if content.get("contribution_to_research"):
            lines.append(f"  - Contribution: {content['contribution_to_research']}")
    if not reports:
        lines.append("- No mission report yet.")
    lines += ["", "## Current hypotheses", ""]
    for hid in hyp_ids:
        h = model["hypotheses"][hid]
        lines += [
            f"### {hid}  [{h['assessment']}]  {h.get('status') or 'active'}",
            f"{h['claim']}",
            f"- Evolution: {len(h['versions'])} versions; evidence: {counts_to(hid, model['evidence'])}",
            "",
        ]
    lines += ["## Evidence", ""]
    found = False
    for eid, e in sorted(model["evidence"].items()):
        if e.get("mission_id") != mission_id:
            continue
        found = True
        lines.append(
            f"- `{eid}` → {e.get('hypothesis_id') or '—'} · direction {_direction_label(e.get('direction'))} · "
            f"verdict {e.get('verdict') or 'pending'}: {e.get('summary') or ''}"
        )
    if not found:
        lines.append("- None yet.")
    lines += ["", "## Decisions", ""]
    decisions = [ev for ev in evs if ev.get("type") == "decision"]
    if decisions:
        for ev in decisions:
            lines.append(f"- ({ev.get('created_at', '')[:19]}) {ev.get('summary', '')}")
    else:
        lines.append("- None yet.")
    lines += ["", "## Open questions and next steps", ""]
    open_questions = [ev.get("summary", "") for ev in evs if ev.get("type") in {"note", "decision"}]
    lines += [f"- {q}" for q in open_questions[-8:]] or ["- To be updated by subsequent tasks."]
    return "\n".join(lines) + "\n"


def _render_chain(model: dict, mission_id: str) -> str:
    """Render replies_to chains as a continuous exchange."""
    by_id = {ev["id"]: ev for ev in model["timeline"]}
    evs = [ev for ev in model["timeline"] if ev.get("mission_id") == mission_id]
    linked = set()
    blocks: list[str] = []
    for ev in evs:
        rid = ev.get("replies_to")
        if rid and rid in by_id:
            prev = by_id[rid]
            linked.update({ev["id"], rid})
            blocks.append(
                f'<div class="chain">'
                f'<span class="tl-time">{_esc((prev.get("created_at") or "")[:19])}</span> '
                f'{_badge(_esc(prev.get("role") or "—"), "b-neu")} {_esc(prev.get("summary") or "")}'
                f'<br>↳ <span class="tl-time">{_esc((ev.get("created_at") or "")[:19])}</span> '
                f'{_badge(_esc(ev.get("role") or "—"), "b-neu")} {_esc(ev.get("summary") or "")}'
                f'</div>'
            )
    unlinked = [ev for ev in evs if ev["id"] not in linked and ev.get("type") not in {"checkpoint"}]
    unlinked_html = "".join(
        f'<div class="chain">{_badge(_esc(ev.get("role") or "—"), "b-neu")} {_esc(ev.get("summary") or "")}</div>'
        for ev in unlinked[-8:]
    )
    return "".join(blocks) + unlinked_html or "<p class=\"muted\">No exchange recorded yet.</p>"


# ---------------------------------------------------------------------------
# Hypothesis lineage view
# ---------------------------------------------------------------------------

def render_hypothesis(run_root: Path, model: dict, hid: str, out_dir: Path, mission_id: str) -> Path:
    h = model["hypotheses"][hid]
    hdir = out_dir / "missions" / mission_id / "hypotheses" / hid
    hdir.mkdir(parents=True, exist_ok=True)
    nav = (
        f'<a href="../../../index.html">Mission</a> '
        f'<a href="../../../timeline.html">Timeline</a> '
        f'<a href="{_esc(hid)}.md">Narrative</a>'
    )
    header = (
        f'<p><code>{_esc(hid)}</code> · {_assessment_badge(h["assessment"])} '
        f'{_badge(_esc(h.get("status") or "active"), "b-neu")}</p>'
        f'<p><strong>Current claim:</strong> {_esc(h["claim"])}</p>'
    )

    version_cards = []
    for i, v in enumerate(h["versions"], 1):
        reply = f'<p class="muted">Reply to event <code>{_esc(v.get("replies_to") or "—")}</code></p>' if v.get("replies_to") else ""
        version_cards.append(
            f'<div class="card"><strong>v{i}</strong> {_badge(_esc(v.get("operation") or ""), "b-neu")} '
            f'{_badge(_esc(v.get("role") or ""), "b-neu")} '
            f'<span class="tl-time">{_esc((v.get("created_at") or "")[:19])}</span>'
            f'{reply}'
            f'<p><em>Change summary:</em> {_esc(v.get("change_summary") or "—")}</p>'
            f'<p>{_esc(v["claim"])}</p>'
            + (f'<p class="muted"><strong>Measurable predictions:</strong> {"; ".join(map(str, v["predictions"]))}</p>' if v.get("predictions") else "")
            + (f'<p class="muted"><strong>Falsifying outcomes:</strong> {"; ".join(map(str, v["falsifiers"]))}</p>' if v.get("falsifiers") else "")
            + (f'<p class="muted"><strong>Scope:</strong> {"; ".join(map(str, v["scope"]))}</p>' if v.get("scope") else "")
            + "</div>"
        )
    lineage_html = "<h2>Evolution (%d versions)</h2>" % len(h["versions"]) + "".join(version_cards)

    ev_rows = []
    for eid, e in sorted(model["evidence"].items()):
        if e.get("hypothesis_id") != hid:
            continue
        ev_rows.append(
            "<tr>"
            f"<td><code>{_esc(eid)}</code></td>"
            f"<td>{_esc(_direction_label(e.get('direction')))}</td>"
            f"<td>{_verdict_badge(e.get('verdict'))}</td>"
            f"<td>{_esc(e.get('summary') or '')}</td>"
            f'<td><a href="../../../evidence/{_esc(eid)}/index.html">Details</a></td>'
            "</tr>"
        )
    evidence_html = (
        "<h2>Evidence balance</h2>"
        + (
            '<table><thead><tr><th>Evidence</th><th>Direction</th><th>Verdict</th><th>Summary</th><th></th></tr></thead>'
            + "".join(ev_rows) + "</table>"
            if ev_rows
            else "<p class=\"muted\">No evidence yet.</p>"
        )
    )

    related = []
    for ev in model["timeline"]:
        if ev.get("mission_id") != mission_id:
            continue
        if ev.get("type") == "challenge" and hid in (ev.get("content") or {}).get("target_ids", []):
            related.append(("<strong>Challenge</strong> " + _esc(ev.get("summary") or ""), ev))
        if ev.get("type") == "review":
            content = ev.get("content") or {}
            e_rec = model["evidence"].get(content.get("evidence_id"))
            if e_rec and e_rec.get("hypothesis_id") == hid:
                related.append(("<strong>Review</strong> " + _esc(ev.get("summary") or ""), ev))
    related_html = (
        "<h2>Related challenges and reviews</h2>"
        + (
            "".join(
                f'<div class="chain"><span class="tl-time">{_esc((e.get("created_at") or "")[:19])}</span> {t}</div>'
                for t, e in related
            )
            if related
            else "<p class=\"muted\">None yet.</p>"
        )
    )

    body = header + lineage_html + evidence_html + related_html
    index_path = hdir / "index.html"
    index_path.write_text(_page(f"Hypothesis Lineage · {hid}", body, nav), encoding="utf-8")

    lines = [
        f"# Hypothesis {hid}",
        "",
        f"- Status: {h.get('status') or 'active'}  Assessment: {h['assessment']}",
        f"- Current claim: {h['claim']}",
        "",
        "## Evolution",
        "",
    ]
    for i, v in enumerate(h["versions"], 1):
        lines += [
            f"### v{i}  operation {v.get('operation') or '—'}  ({(v.get('created_at') or '')[:19]})",
            f"- Change summary: {v.get('change_summary') or '—'}",
            f"- Claim: {v['claim']}",
            f"- Predictions: {'; '.join(map(str, v.get('predictions') or [])) or '—'}",
            f"- Falsifiers: {'; '.join(map(str, v.get('falsifiers') or [])) or '—'}",
            f"- Scope: {'; '.join(map(str, v.get('scope') or [])) or '—'}",
            "",
        ]
    lines += ["## Evidence balance", ""]
    for eid, e in sorted(model["evidence"].items()):
        if e.get("hypothesis_id") == hid:
            lines.append(f"- `{eid}` direction {_direction_label(e.get('direction'))} verdict {e.get('verdict') or 'pending'}: {e.get('summary') or ''}")
    md_path = hdir / f"{hid}.md"
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return index_path


# ---------------------------------------------------------------------------
# Evidence view
# ---------------------------------------------------------------------------

def render_evidence(run_root: Path, model: dict, eid: str, out_dir: Path) -> Path:
    e = model["evidence"][eid]
    edir = out_dir / "missions" / (e.get("mission_id") or "") / "evidence" / eid
    edir.mkdir(parents=True, exist_ok=True)
    nav = (
        f'<a href="../../../index.html">Mission</a> '
        f'<a href="../../../hypotheses/{_esc(e.get("hypothesis_id") or "")}/index.html">Hypothesis lineage</a>'
    )
    body = (
        f'<p><code>{_esc(eid)}</code> · hypothesis <code>{_esc(e.get("hypothesis_id") or "—")}</code> · '
        f'direction {_esc(_direction_label(e.get("direction")))} · {_verdict_badge(e.get("verdict"))}</p>'
        f'<p><strong>{_esc(e.get("summary") or "")}</strong></p>'
        f'<p>{_esc(e.get("narrative") or "")}</p>'
        f'<p class="muted">Reviewer: {_esc(e.get("review_role") or "—")}'
        f'  Review reasons: {_esc(e.get("verdict_reason") or "—")}</p>'
    )
    path = edir / "index.html"
    path.write_text(_page(f"Evidence · {eid}", body, nav), encoding="utf-8")

    md = (
        f"# Evidence {eid}\n\n"
        f"- Hypothesis: `{e.get('hypothesis_id') or '—'}`  Direction: {_direction_label(e.get('direction'))}  Verdict: {e.get('verdict') or 'pending'}\n"
        f"- Summary: {e.get('summary') or ''}\n"
        f"- Narrative: {e.get('narrative') or ''}\n"
        f"- Reviewer: {e.get('review_role') or '—'}; reasons: {e.get('verdict_reason') or '—'}\n"
    )
    md_path = edir / f"{eid}.md"
    md_path.write_text(md, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Task trajectory view
# ---------------------------------------------------------------------------

def render_task(run_root: Path, model: dict, tid: str, out_dir: Path) -> Path:
    t = model["tasks"][tid]
    mission_id = None
    for ev in model["timeline"]:
        if ev.get("task_id") == tid:
            mission_id = ev.get("mission_id") or mission_id
    mission_id = mission_id or ""
    tdir = out_dir / "missions" / mission_id / "tasks"
    tdir.mkdir(parents=True, exist_ok=True)
    nav = '<a href="../../index.html">Mission</a>'
    header = (
        f'<p><code>{_esc(tid)}</code> · role {_badge(_esc(t.get("role") or "—"), "b-neu")}'
        f' · start {_esc((t.get("start") or "")[:19])} · end {_esc((t.get("end") or "")[:19])}</p>'
    )
    nodes = []
    for ev in t["events"]:
        content = ev.get("content") or {}
        details = []
        for key, label in (
            ("tool_name", "Tool"), ("command", "Command"), ("exit_code", "Exit code"),
            ("wall_seconds", "Wall seconds"), ("status", "Status"), ("attempt_index", "Attempt"),
            ("input_summary", "Input"), ("output_summary", "Output"), ("error", "Error"),
            ("progress_ts", "Recorded at"),
        ):
            v = content.get(key)
            if v is not None:
                details.append(f"<dt>{label}</dt><dd><code>{_esc(v)}</code></dd>")
        arts = content.get("artifact_files") or []
        if arts:
            details.append("<dt>Artifacts</dt><dd>"
                           + ", ".join(f"<code>{_esc(a)}</code>" for a in arts) + "</dd>")
        dl = f"<dl>{''.join(details)}</dl>" if details else ""
        nodes.append(
            f'<div class="tl-item"><span class="tl-time">{_esc((ev.get("created_at") or "")[:19])}</span> '
            f'{_badge(_esc(ev.get("kind") or ""), "b-neu")} '
            f'<strong>{_esc(ev.get("summary") or "")}</strong>{dl}</div>'
        )
    body = header + "<h2>Task trajectory (%d nodes)</h2><div class=\"timeline\">" % len(nodes) + "".join(nodes) + "</div>"
    path = tdir / f"{tid}.html"
    path.write_text(_page(f"Task Trajectory · {tid}", body, nav), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Task board view
# ---------------------------------------------------------------------------

def _task_status(t: dict) -> str:
    """Derive the task status from its trace events."""
    kinds = {ev.get("kind") for ev in t["events"]}
    if "task_end" in kinds:
        return "completed"
    if "delivery_received" in kinds:
        return "delivered"
    if "attempt_start" in kinds or "tool_run" in kinds:
        return "in_progress"
    if "task_start" in kinds:
        return "started"
    return "assigned"


def _task_counts(t: dict) -> dict:
    kinds = [ev.get("kind") for ev in t["events"]]
    return {
        "attempts": kinds.count("attempt_start"),
        "tool_runs": kinds.count("tool_run"),
        "nodes": len(t["events"]),
    }


def render_task_board(run_root: Path, model: dict, mission_id: str, out_dir: Path) -> Path:
    """Write missions/<MIS>/tasks/index.html: per-task cards derived from traces."""
    tdir = out_dir / "missions" / mission_id / "tasks"
    tdir.mkdir(parents=True, exist_ok=True)
    nav = (
        '<a href="../../index.html">Mission</a> '
        '<a href="../../timeline.html">Timeline</a>'
    )
    status_cls = {
        "completed": "b-ok", "delivered": "b-wait", "in_progress": "b-h",
        "started": "b-neu", "assigned": "b-p",
    }
    cards = []
    for tid, t in sorted(model["tasks"].items()):
        in_mission = any(
            ev.get("mission_id") == mission_id
            for ev in model["timeline"]
            if ev.get("task_id") == tid
        )
        if not in_mission:
            continue
        status = _task_status(t)
        counts = _task_counts(t)
        cards.append(
            f'<div class="card"><strong><code>{_esc(tid)}</code></strong> '
            f'{_badge(_esc(t.get("role") or "—"), "b-neu")} '
            f'{_badge(status, status_cls.get(status, "b-p"))}'
            f'<p class="muted">attempts {counts["attempts"]} · tool runs {counts["tool_runs"]} · '
            f'{counts["nodes"]} trace nodes · start {_esc((t.get("start") or "")[:19])}'
            f' · end {_esc((t.get("end") or "")[:19])}</p>'
            f'<a href="{_esc(tid)}.html">View trace →</a></div>'
        )
    body = (
        f"<h2>Task board</h2>"
        + ("".join(cards) if cards else "<p class=\"muted\">No tasks yet.</p>")
    )
    path = tdir / "index.html"
    path.write_text(_page(f"Task Board · {mission_id}", body, nav), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Main entry
# ---------------------------------------------------------------------------

def render_all(run_root: Path, checkpoint: bool = False) -> list[str]:
    """Rebuild all views. Return the list of written file paths relative to the run root."""
    from events import write_checkpoint, validate_log

    errors = validate_log(run_root)
    if errors:
        raise ValueError("Log validation failed; refusing to render:\n  - " + "\n  - ".join(errors))

    model = build_model(run_root)
    out_dir = run_root / "blackboard"
    out_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    written.append(render_campaign(run_root, model, out_dir)[0])
    written.append("blackboard/README.md")
    written.append(str(render_global_timeline(run_root, model, out_dir).relative_to(run_root)))
    written.append(str(render_experience(run_root, out_dir).relative_to(run_root)))
    written.append(str(render_research_snapshot(run_root, model, out_dir).relative_to(run_root)))
    written += render_directives_pages(run_root, out_dir)

    for mission_id in model["missions"]:
        written.append(str(render_mission(run_root, model, mission_id, out_dir).relative_to(run_root)))
        written.append(f"blackboard/missions/{mission_id}/report.md")
        written.append(f"blackboard/missions/{mission_id}/timeline.html")
        written.append(str(render_task_board(run_root, model, mission_id, out_dir).relative_to(run_root)))

    for hid in model["hypotheses"]:
        h = model["hypotheses"][hid]
        mid = h.get("mission_id") or model.get("last_mission_id") or ""
        written.append(str(render_hypothesis(run_root, model, hid, out_dir, mid).relative_to(run_root)))
        written.append(f"blackboard/missions/{mid}/hypotheses/{hid}/{hid}.md")

    for eid in model["evidence"]:
        written.append(str(render_evidence(run_root, model, eid, out_dir).relative_to(run_root)))
        written.append(f"blackboard/missions/{model['evidence'][eid].get('mission_id') or ''}/evidence/{eid}/{eid}.md")

    for tid in model["tasks"]:
        written.append(str(render_task(run_root, model, tid, out_dir).relative_to(run_root)))

    if checkpoint:
        ck = write_checkpoint(run_root, model)
        written.append(f"blackboard/checkpoints/{ck['id']}.json")

    return written


def _cli() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Rebuild all blackboard views")
    parser.add_argument("run_root", help="run root directory")
    parser.add_argument("--checkpoint", action="store_true", help="also write a checkpoint after rendering")
    args = parser.parse_args()
    try:
        written = render_all(Path(args.run_root).resolve(), checkpoint=args.checkpoint)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"Wrote {len(written)} files:")
    for w in written:
        print("  " + w)
    return 0


if __name__ == "__main__":
    sys.exit(_cli())